# Generated by Django 3.1 on 2021-03-26 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0009_gym_state'),
        ('mailer', '0002_auto_20190618_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='gym',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='email_log', to='gym.gym'),
        ),
    ]
