# Generated by Django 3.1 on 2021-02-03 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0008_auto_20190618_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='state',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='State'),
        ),
    ]
