# Generated by Django 3.1 on 2021-04-02 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0009_gym_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='city',
            field=models.CharField(blank=True, default='Some City', max_length=30, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='gym',
            name='state',
            field=models.CharField(blank=True, default='NV', max_length=30, verbose_name='State'),
        ),
    ]
