# Generated by Django 3.1 on 2021-04-02 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0010_auto_20210402_0450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='city',
            field=models.CharField(blank=True, default='Good City', max_length=30, verbose_name='City'),
        ),
    ]
