# Generated by Django 3.1 on 2021-01-31 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210131_0235'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='goal',
            field=models.CharField(default='', max_length=20, verbose_name='goal'),
        ),
    ]
