# Generated by Django 3.1 on 2021-02-04 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_userprofile_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='fitness_activity',
            field=models.CharField(choices=[('0', 'Cross Fit'), ('1', 'Bodybuilding'), ('2', 'Cardio'), ('3', 'Power Lifting'), ('4', 'General Fitness')], default='2', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='goal',
            field=models.CharField(choices=[('0', 'Lose Weight'), ('1', 'Gain Weight'), ('2', 'Get Active'), ('3', 'Start Learning')], default='0', max_length=20, null=True),
        ),
    ]
