# Generated by Django 3.1 on 2021-02-04 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210204_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='goal',
            field=models.CharField(choices=[('LW', 'Lose Weight'), ('BB', 'Bodybuilding'), ('CF', 'Cross Fit')], default='LW', max_length=20, null=True),
        ),
    ]
