# Generated by Django 3.1 on 2021-03-26 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210204_0822'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_creator_name', models.CharField(max_length=20, verbose_name='Name')),
                ('content', models.CharField(max_length=200, verbose_name='Content')),
                ('content_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
