# Generated by Django 3.1 on 2021-03-26 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_contentmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(default='some value', max_length=50, verbose_name='Post Title')),
                ('post_creator_name', models.CharField(max_length=20, verbose_name='Name')),
                ('post_content', models.CharField(max_length=200, verbose_name='Content')),
                ('content_date', models.DateTimeField(auto_now_add=True)),
                ('replies', models.ManyToManyField(related_name='_postmodel_replies_+', to='core.ContentModel')),
            ],
        ),
    ]
