# Generated by Django 3.1 on 2021-03-27 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_postmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_name', models.CharField(max_length=20, verbose_name='Forum Name')),
                ('posts', models.ManyToManyField(to='core.PostModel')),
            ],
        ),
        migrations.CreateModel(
            name='ForumCategoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forum_category_name', models.CharField(max_length=20, verbose_name='Forum Category')),
                ('forums', models.ManyToManyField(to='core.ForumModel')),
            ],
        ),
    ]
