# Generated by Django 3.1 on 2021-03-28 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_forumcategorymodel_forummodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='forummodel',
            name='slug',
            field=models.SlugField(default='some-slug'),
        ),
    ]
