# Generated by Django 3.1 on 2021-03-28 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_postmodel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='forummodel',
            name='description',
            field=models.CharField(default='Forum Description', max_length=100, verbose_name='Forum Description'),
        ),
    ]
